default_platform(:ios)

platform :ios do
  lane :internal do
    setup_ci if ENV['CI']
    sync_code_signing(type: "appstore", readonly: true)
    app_store_connect_api_key(duration: 1200) if ENV['CI']

    sh(
      "flutter", "build", "ipa",
      "--obfuscate",
      "--split-debug-info=debug-info",
      "--release",
    )
    upload_to_testflight(
      ipa: ipaPath,
      skip_waiting_for_build_processing: ENV['CI'],
    )
  end

  def ipaPath
    name = get_info_plist_value(path: "./Runner/Info.plist", key: "CFBundleName")
    return "../build/ios/ipa/#{name}.ipa"
  end
end
