default_platform(:ios)

platform :ios do
  lane :internal do
    setup_ci if ENV['CI']
    sync_code_signing(type: "appstore", readonly: true)
    app_store_connect_api_key(duration: 1200) if ENV['CI']
    build_number = latest_testflight_build_number + 1

    exportOptionsFilePath = "#{Tempfile.new('exportOptions').path}.plist"
    File.write(exportOptionsFilePath, {
      method: "app-store",
      uploadBitcode: false,
      provisioningProfiles: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING],
    }.to_plist)

    sh(
      "flutter", "build", "ipa",
      "--obfuscate",
      "--split-debug-info=debug-info",
      "--release",
      "--build-number=#{build_number}",
      "--export-options-plist=#{exportOptionsFilePath}"
    )
    upload_to_testflight(
      ipa: ipaPath,
      skip_waiting_for_build_processing: ENV['CI'],
    )
  ensure
    File.delete(exportOptionsFilePath) if File.exist?(exportOptionsFilePath)
  end

  def ipaPath
    name = get_info_plist_value(path: "./Runner/Info.plist", key: "CFBundleName")
    return "../build/ios/ipa/#{name}.ipa"
  end
end
