name: build and publish (android)

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build Android App and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > android/key.properties
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - name: Run Fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
        working-directory: android
