name: build and publish (iOS)

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    name: Build iOS App and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CERTIFICATION_DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - name: Run Fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        working-directory: android
